spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud_system?characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: root
    hikari: #连接池
      maximum-pool-size: 20 # 连接池最大连接数，默认是10
      minimum-idle: 10 # 最小空闲连接数量
  application:
    name: spring-cloud-client #服务中心服务名

server:
  port: 8001 #服务中心端口号

eureka: #Eureka 服务中心相关配置
  instance:
    prefer-ip-address: true #没有这行你休想访问不同电脑的swagger接口
    hostname: localhost
    lease-renewal-interval-in-seconds: 20 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 30 # 如果现在超过了5秒的间隔（默认是90秒）
  client:
    register-with-eureka: true #是否将eureka自身作为应用注册到eureka注册中心
    fetch-registry: true #是否把自己作为服务注册到其他服务注册中心
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8000/eureka/  #指向注册中心配置路径

mybatis-plus:
  type-aliases-package: com.example.spring.cloud.client.entity #指定实体类别名
  mapper-locations: classpath:com/example/spring/cloud/client/mapper/mapping/*.xml
